### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by pjebs** [callumboddy/CBZSplashView#24]
Cocoapods seems to only include CBZSplashView

**Comment by pjebs** [comment]
The pod specs seems to set up correctly: "s.source_files  = 'Pod/Classes', '*.{h,m}'"
For some reason, only CBZSplashView gets downloaded and loaded

**Comment by jamesanse** [comment]
same problem

**Comment by tbaranes** [comment]
+1

**Comment by cwveysey** [comment]
I was able to get things working by manually adding CBZRasterSplashView.h, CBZRasterSplashView.m,
CBZVectorSplashView.h, and CBZVectorSplashView.m to my project (I cloned the example project / grabbed em from there - I already had CBZSplashView.h and CBZSplashView.m via the CocoaPod).

**Comment by pjebs** [comment]
That's what I did but obviously its nice to operate as much as possible in the CocoaPods world.

**Comment by pjebs** [comment]
I sent him an email. The issue  the pod spec file links to the "1.0.0" tag in his repository. In that tag, only CBZSplashView.h and CBZSplashView.m exist so that is all CocoaPods downloads.

**Comment by pjebs** [comment]
I sent him an email but no response.
It's possible he may have passed away :( RIP

I'll make a fork and add it to cocoapods soon

**Comment by Mazyod** [comment]
Hey guys, I'm late to the party as usual, but I have some time on my hands now. I'll try to update the cocoapods today if that works for you

**Comment by Mazyod** [comment]
in case you are interested, he is alive and well :) You may not be reaching him, or he's probably just too busy to look into this repo for the time being https://twitter.com/callumboddy/status/606405392873193473

**Comment by pjebs** [comment]
Ok with me.

How did you get permission to add bug label?

**Comment by Mazyod** [comment]
@pjebs As it says, I am a collaborator on this repo, callumboddy agreed to add me when I contributed the bezier path approach.

**Comment by Mazyod** [comment]
Well, I tried to make a new cocoapods release, just to be safe, but that didn't work because apparently I don't have permissions to make a new cocoapods release. I updated the `1.0.0` tag reference, but that is sub optimal, because some cache may exist somewhere, and also might break stuff for existing users of the `1.0.0` version...

¯\_(ツ)_/¯

**Comment by callumboddy** [comment]
Sorry have been away guys, also very busy at work atm.. thank you very much for doing that @Mazyod . I think it should be fine.

**Comment by pjebs** [comment]
The v1.0.1 tag hasn't been created.

**Comment by Mazyod** [comment]
Anytime @callumboddy~! I'll try to help out, feel free to assign me to stuff if you find an urgent issue.

@pjebs Yes, I created it, then removed it since I didn't have permission to bump the project version. You should clear your Cocoapods cache, and try to install v1.0.0 again.
